apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
  - port: 8686
    targetPort: 8686
    nodePort: 30080

